# Generated by Django 5.2.2 on 2025-06-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartCity_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ambientes',
            options={'verbose_name_plural': 'Ambientes'},
        ),
        migrations.AlterModelOptions(
            name='sensores',
            options={'verbose_name_plural': 'Sensores'},
        ),
        migrations.AlterField(
            model_name='historico',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
