# Generated by Django 5.2.2 on 2025-06-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartCity_app', '0002_alter_ambientes_options_alter_sensores_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='funcao',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Professor', 'Professor')], default='Aluno', max_length=30),
        ),
    ]
