# Generated by Django 5.2.2 on 2025-06-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartCity_app', '0003_alter_usuario_funcao'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioCadastrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('senha', models.CharField(max_length=50)),
                ('confirmarSenha', models.CharField(max_length=50)),
            ],
        ),
    ]
