# Generated by Django 5.2.2 on 2025-06-13 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SmartCity_app', '0004_usuariocadastrado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsuarioCadastrado',
        ),
    ]
